-- Creating the ROOM table
CREATE TABLE ROOM (
    ROOMID VARCHAR(10) PRIMARY KEY,
    ROOMNUMBER NUMBER,
    ROOMTYPE VARCHAR(20),
    RATE NUMBER,
    DESCRIPTION CLOB,
    BEDTYPE VARCHAR(20)
);

-- Creating the GUEST table
CREATE TABLE GUEST (
    GUESTID VARCHAR(10) PRIMARY KEY,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(50)
);

-- Creating the ROOMTYPE table
CREATE TABLE ROOMTYPE (
    ROOMTYPEID INT PRIMARY KEY,
    TYPENAME VARCHAR(50)
);

-- Creating the RESERVATION table
CREATE TABLE RESERVATION (
    RESERVATIONID VARCHAR(10) PRIMARY KEY,
    GUESTID VARCHAR(10),
    ROOMID VARCHAR(10),
    CHECKINDATE DATE,
    CHECKOUTDATE DATE,
    RESERVATIONDATE DATE,
    TOTALAMOUNT DECIMAL(10, 2),
    PAYMENTSTATUS VARCHAR(20),
    FOREIGN KEY (GUESTID) REFERENCES GUEST(GUESTID),
    FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID)
);

-- Creating the PAYMENT table
CREATE TABLE PAYMENT (
    PAYMENTID VARCHAR(10) PRIMARY KEY,
    RESERVATIONID VARCHAR(10),
    PAYMENTDATE DATE,
    PAIDAMOUNT DECIMAL(10, 2),
    PENDINGAMOUNT DECIMAL(10, 2),
    PAYMENTMETHOD VARCHAR(20),
    FOREIGN KEY (RESERVATIONID) REFERENCES RESERVATION(RESERVATIONID)
);
