INSERT INTO ROOMTYPE (ROOMTYPEID, TYPENAME) VALUES (1, 'Standard');
INSERT INTO ROOMTYPE (ROOMTYPEID, TYPENAME) VALUES (2, 'Deluxe');
INSERT INTO ROOMTYPE (ROOMTYPEID, TYPENAME) VALUES (3, 'Double');
INSERT INTO ROOMTYPE (ROOMTYPEID, TYPENAME) VALUES (4, 'Suite');
INSERT INTO ROOMTYPE (ROOMTYPEID, TYPENAME) VALUES (5, 'Penthouse');
