INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY101', 'RS201', TO_DATE('2023-11-20', 'YYYY-MM-DD'), 1800, 0, 'online');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY102', 'RS202', TO_DATE('2023-10-01', 'YYYY-MM-DD'), 3800, 0, 'debit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY103', 'RS203', TO_DATE('2023-09-04', 'YYYY-MM-DD'), 140, 0, 'debit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY104', 'RS204', TO_DATE('2023-12-08', 'YYYY-MM-DD'), 100, 80, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY105', 'RS205', TO_DATE('2023-12-02', 'YYYY-MM-DD'), 150, 0, 'credit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY106', 'RS206', TO_DATE('2023-10-12', 'YYYY-MM-DD'), 480, 0, 'debit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY107', 'RS207', TO_DATE('2023-12-21', 'YYYY-MM-DD'), 200, 40, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY108', 'RS208', TO_DATE('2023-12-04', 'YYYY-MM-DD'), 40, 60, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY109', 'RS209', TO_DATE('2023-06-12', 'YYYY-MM-DD'), 420, 0, 'credit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY110', 'RS210', TO_DATE('2023-06-03', 'YYYY-MM-DD'), 960, 0, 'credit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY111', 'RS211', TO_DATE('2023-11-07', 'YYYY-MM-DD'), 50, 0, 'online');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY112', 'RS212', TO_DATE('2023-10-19', 'YYYY-MM-DD'), 720, 0, 'debit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY113', 'RS213', TO_DATE('2023-02-15', 'YYYY-MM-DD'), 320, 0, 'debit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY114', 'RS214', TO_DATE('2023-12-13', 'YYYY-MM-DD'), 250, 50, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY115', 'RS215', TO_DATE('2023-12-16', 'YYYY-MM-DD'), 600, 30, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY116', 'RS216', TO_DATE('2023-11-09', 'YYYY-MM-DD'), 360, 0, 'credit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY117', 'RS217', TO_DATE('2023-05-05', 'YYYY-MM-DD'), 1520, 0, 'credit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY118', 'RS218', TO_DATE('2023-08-01', 'YYYY-MM-DD'), 2660, 0, 'debit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY119', 'RS219', TO_DATE('2023-12-29', 'YYYY-MM-DD'), 50, 100, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY120', 'RS220', TO_DATE('2023-12-23', 'YYYY-MM-DD'), 1000, 120, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY121', 'RS221', TO_DATE('2023-10-03', 'YYYY-MM-DD'), 650, 0, 'credit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY122', 'RS222', TO_DATE('2023-07-06', 'YYYY-MM-DD'), 1920, 0, 'credit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY123', 'RS223', TO_DATE('2023-06-12', 'YYYY-MM-DD'), 160, 0, 'online');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY124', 'RS224', TO_DATE('2023-01-02', 'YYYY-MM-DD'), 2000, 0, 'debit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY125', 'RS225', TO_DATE('2023-07-08', 'YYYY-MM-DD'), 2100, 0, 'debit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY126', 'RS226', TO_DATE('2023-12-23', 'YYYY-MM-DD'), 400, 400, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY127', 'RS227', TO_DATE('2023-11-02', 'YYYY-MM-DD'), 1470, 0, 'credit card');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY128', 'RS228', TO_DATE('2023-12-25', 'YYYY-MM-DD'), 2000, 160, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY129', 'RS229', TO_DATE('2023-12-25', 'YYYY-MM-DD'), 250, 250, 'Cash');

INSERT INTO PAYMENT (PAYMENTID, RESERVATIONID, PAYMENTDATE, PAIDAMOUNT, PENDINGAMOUNT, PAYMENTMETHOD) 
VALUES ('PY130', 'RS230', TO_DATE('2023-10-12', 'YYYY-MM-DD'), 360, 0, 'credit card');
